services:
  - type: web
    name: clonify
    env: python
    buildCommand: |
      pip install -r requirements.txt
      bash install_ffmpeg.sh
    startCommand: gunicorn -w 4 -b 0.0.0.0:8000 app:app
